Java05. ДЗ 01, Горячева Валерия
lergor/JAVA pull request #2
Opened 2018-03-07 12:47 UTC by lergor

2018-03-16 07:59 UTC, lergor commented
Я забыла вызывать метод checkAndDelete, добавила его вызов при удалении элемента из бора.

2018-03-16 09:37 UTC, lergor commented
Исправила баг, добавила тест, который вы привели на паре.

2018-03-18 15:36 UTC, sproshev requested changes

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +    private Node[] next;
final

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +            if(next[getIndex(letter)] == null) {
если здесь false, то переход удалится (

лучше `getIndex(letter)` выделить в переменную, зачем 3 раза вычислять

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +        if(nextNode != null && nextNode.stringsCount == 0 && !nextNode.isTerminal()) {
если узел терминальный, разве его размер не должен быть 1 (пустая строка)?

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +        if(nextNode != null && nextNode.stringsCount == 0 && !nextNode.isTerminal()) {
аналогично getIndex в переменную

2018-03-18 15:36 UTC, sproshev commented on trie/src/test/java/ru/spbau/mit/trie/TrieImplTest.java
> +            assertEquals(testTrie.size(), i + 1);
сперва ожидамое значение, потом актуальное

2018-03-18 15:36 UTC, sproshev commented on trie/src/test/java/ru/spbau/mit/trie/TrieImplTest.java
> +    public void test1() {
лучше комментарий в таком случае в имя метода перенести

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +        if(element.length() > 0) {
после `if` должен быть пробел

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +        Node f = root;
unused

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +    public void setState(char letter, boolean adding) {
этот метод используется 1 раз с adding = true, лучше упростить и переименовать

2018-03-18 15:36 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +        }
`final int num = adding ? 1 : -1;`

2018-03-22 20:04 UTC, lergor commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +        if(nextNode != null && nextNode.stringsCount == 0 && !nextNode.isTerminal()) {
@sproshev Но тут проверка на то, что следующая нода не терминальная и дальше в этой ветке не содержится слов, то есть stringsCount = 0

2018-03-22 20:10 UTC, lergor commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +        if(nextNode != null && nextNode.stringsCount == 0 && !nextNode.isTerminal()) {
Вообще, вы правы, я не увеличивала счетчик в терминальной ноде, исправила это.

2018-03-24 18:03 UTC, sproshev approved these changes

2018-03-24 18:03 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +    private static Node root = new Node();
? почему статик?

2018-03-24 18:03 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +        if (element.length() > 0) {
см метод isEmpty

2018-03-24 18:03 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/Node.java
> +        terminalState = state;
сеттер не должен производить никаких побочных эффектов, кроме обновления упомянутого в имени поля
лучше или переименовать, или разбить на два вызова

2018-03-24 18:03 UTC, sproshev commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +    private static Node root = new Node();
из-за этого модификатора все экземпляры бора будут иметь один корень и одно содержание

2018-03-25 00:03 UTC, lergor commented on trie/src/main/java/ru/spbau/mit/trie/TrieImpl.java
> +    private static Node root = new Node();
@sproshev Да, верно, исправила.

2018-06-26 07:11 UTC, merged