Java05. ДЗ 04, Горячева Валерия
lergor/JAVA pull request #5
Opened 2018-04-26 23:50 UTC by lergor

2018-05-01 19:00 UTC, sproshev requested changes

2018-05-01 19:00 UTC, sproshev commented on functional_java/src/main/java/ru/spbau/mit/Predicate.java
> +    Boolean apply(T argument);
эту строку можно стереть, метод унаследуется от Function1

2018-05-01 19:00 UTC, sproshev commented on functional_java/src/main/java/ru/spbau/mit/Function1.java
> +        return argument -> other.apply(this.apply(argument));
this не нужен

2018-05-01 19:00 UTC, sproshev commented on functional_java/src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private ArrayList<Integer> numbers = new ArrayList<>();
не проверяются ? extends ..., ? super ...

2018-05-01 19:00 UTC, sproshev commented on functional_java/src/test/java/ru/spbau/mit/PredicateTest.java
> +        assertThat(lazyFalse.apply(17)).isFalse();
это не проверяет ленивость, ленивость это когда что-то вызывается при необходимости, т.е. надо проверить, что один из предикатов не вызывался

2018-05-17 21:10 UTC, lergor commented on functional_java/src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private ArrayList<Integer> numbers = new ArrayList<>();
@sproshev Исправила.

2018-06-26 07:12 UTC, merged