Java05. ДЗ 05, Горячева Валерия
lergor/JAVA pull request #6
Opened 2018-05-18 00:58 UTC by lergor

2018-05-28 21:46 UTC, sproshev requested changes

2018-05-28 21:46 UTC, sproshev commented on stream_api/src/main/java/ru/spbau/mit/FirstPartTasks.java
> +        return "<" + body + ">";
постоянное складывание строк это жор всего, что только можно, см Collectors.joining

2018-05-28 21:46 UTC, sproshev commented on stream_api/src/main/java/ru/spbau/mit/SecondPartTasks.java
> +                .max(Comparator.comparing(e -> String.join("", e.getValue()).length()))
аналогично, надо обойтись без сложения строк

2018-05-28 21:46 UTC, sproshev commented on stream_api/src/test/java/ru/spbau/mit/SecondPartTasksTest.java
> +                Arrays.asList("file.txt"), "kek"))
Collections.singletonList

2018-05-29 12:35 UTC, lergor commented
@sproshev Исправила.

2018-05-30 20:13 UTC, sproshev commented on stream_api/src/main/java/ru/spbau/mit/SecondPartTasks.java
> +                .max(Comparator.comparing(e -> String.join("", e.getValue()).length()))
.max(Comparator.comparingInt(e -> e.getValue().stream().mapToInt(String::length).sum()))

2018-06-26 07:47 UTC, merged